backend:
  name: github
  repo: aadel7/equishare-astro
  branch: main
  site_domain: equishare-stem4kids.vercel.app # Replace with your site's domain
  base_url: https://equishare-stem4kids.vercel.app # Replace with your production URL
  auth_endpoint: oauth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "post-{{year}}-{{month}}-{{day}}"
    extension: mdx
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
